// RuralCare Connect - Telemedicine Platform for Nabha, Punjab (SIH25018)
// mock data, symptom maps, and multilingual translation dictionary

const RURALCARE_DATA = {
  // Translations database for English, Hindi (हिन्दी), Punjabi (ਪੰਜਾਬੀ), and Odia (ଓଡ଼ିଆ)
  translations: {
    en: {
      nav_services: "Services",
      nav_doctors: "Find Doctors",
      nav_ai: "AI Health",
      nav_awareness: "Awareness",
      nav_contact: "Contact",
      nav_login: "Login",
      nav_register: "Register Free",
      hero_sih: "Smart India Hackathon 2025 – SIH25018",
      hero_badge: "Telemedicine Platform for Nabha, Punjab",
      hero_title: "Quality Healthcare Reaches Every Village",
      hero_desc: "AI-powered telemedicine connecting rural communities in Nabha and beyond with qualified doctors — anytime, anywhere, in your language.",
      btn_consult: "Consult a Doctor",
      btn_ai: "Try AI Checker",
      stats_doctors: "Verified Doctors",
      stats_consultations: "Consultations Done",
      stats_specialties: "Specializations",
      stats_languages: "Languages",
      stats_emergency: "24/7 Emergency Access",
      search_title: "Search Doctors, Symptoms or Diseases",
      search_placeholder: "Symptoms, doctor name, specialization...",
      search_location: "Location (Nabha, Patiala...)",
      search_btn: "Search Doctors",
      services_title: "Complete Rural Healthcare Ecosystem",
      services_subtitle: "What We Offer",
      services_desc: "Built for low-bandwidth environments, providing vital healthcare services to rural citizens.",
      steps_title: "Get Doctor Consultation in 4 Steps",
      steps_subtitle: "Simple Process",
      step1_title: "Register Free",
      step1_desc: "Create your patient profile in English, Hindi, Punjabi or Odia. No tech skills needed.",
      step2_title: "AI Checks Symptoms",
      step2_desc: "Describe symptoms by voice or text. AI recommends the right specialist and urgency.",
      step3_title: "Book Appointment",
      step3_desc: "Choose a verified doctor, pick a slot that suits you, and get instant confirmation.",
      step4_title: "Video Consult",
      step4_desc: "Join low-bandwidth video/audio call, get diagnosed, receive digital prescription.",
      ai_header: "AI-Powered Healthcare",
      ai_title: "Smart Diagnosis. Right Doctor. Right Now.",
      ai_desc: "Our AI engine trained on clinical protocols instantly analyzes your symptoms in local languages, recommending the best matching doctor.",
      ai_engine: "AI Doctor Recommendation Engine",
      ai_engine_desc: "Matches symptoms to the right specialist with 90%+ accuracy",
      ai_multilingual: "Multilingual AI Assistant",
      ai_multilingual_desc: "Speaks Hindi, Punjabi, Odia — natural regional language support",
      ai_emergency: "Emergency Prioritization System",
      ai_emergency_desc: "Automatically classifies severity and triggers emergency protocols",
      ai_prediction: "Rural Health Risk Prediction",
      ai_prediction_desc: "Predicts seasonal outbreaks using regional Nabha healthcare data",
      ai_chat_title: "RuralCare AI Assistant",
      ai_chat_subtitle: "Online · Responds instantly",
      ai_chat_placeholder: "Type symptoms (e.g. chest pain, fever, cough)...",
      emergency_title: "EMERGENCY: Urgent Care Needed?",
      emergency_desc: "One-tap SOS, ambulance booking, blood bank info, and Nabha Civil Hospital locator.",
      emergency_btn_sos: "Activate SOS Alarm",
      emergency_btn_amb: "Request Ambulance",
      doctors_title: "500+ Verified Doctors Ready to Help",
      doctors_subtitle: "Our Specialists",
      btn_book: "Book Appointment",
      patient_records_title: "Patient Digital Health Vault",
      patient_records_desc: "Access your e-prescriptions, upload medical reports, and track your vital trends over time.",
      vitals_header: "Your Health Vitals History",
      prescriptions_header: "Your Digital Prescriptions",
      upload_btn: "Upload Lab Report",
      low_bandwidth_active: "Low-Bandwidth Mode Active: Compressing media and prioritizing audio/text consultations.",
      low_bandwidth_inactive: "Normal Mode: High-definition video enabled."
    },
    hi: {
      nav_services: "सेवाएं",
      nav_doctors: "डॉक्टर खोजें",
      nav_ai: "एआई स्वास्थ्य",
      nav_awareness: "जागरूकता",
      nav_contact: "संपर्क करें",
      nav_login: "लॉगिन",
      nav_register: "मुफ़्त पंजीकरण",
      hero_sih: "स्मार्ट इंडिया हैकाथॉन 2025 – SIH25018",
      hero_badge: "नाभा, पंजाब के लिए टेलीमेडिसिन प्लेटफॉर्म",
      hero_title: "गुणवत्तापूर्ण स्वास्थ्य सेवा हर गाँव तक पहुँचे",
      hero_desc: "एआई-संचालित टेलीमेडिसिन जो नाभा और उसके आसपास के ग्रामीण समुदायों को योग्य डॉक्टरों से जोड़ती है - कभी भी, कहीं भी, आपकी भाषा में।",
      btn_consult: "डॉक्टर से परामर्श लें",
      btn_ai: "एआई चेकर आजमाएं",
      stats_doctors: "सत्यापित डॉक्टर",
      stats_consultations: "परामर्श संपन्न",
      stats_specialties: "विशेषज्ञता",
      stats_languages: "भाषाएँ",
      stats_emergency: "24/7 आपातकालीन पहुंच",
      search_title: "डॉक्टर, लक्षण या बीमारियों की खोज करें",
      search_placeholder: "लक्षण, डॉक्टर का नाम, विशेषज्ञता...",
      search_location: "स्थान (नाभा, पटियाला...)",
      search_btn: "डॉक्टर खोजें",
      services_title: "पूर्ण ग्रामीण स्वास्थ्य सेवा पारिस्थितिकी तंत्र",
      services_subtitle: "हमारी पेशकश",
      services_desc: "कम बैंडविड्थ वाले क्षेत्रों के लिए डिज़ाइन किया गया, जो ग्रामीण नागरिकों को आवश्यक स्वास्थ्य सेवाएं प्रदान करता है।",
      steps_title: "4 आसान चरणों में डॉक्टर का परामर्श प्राप्त करें",
      steps_subtitle: "सरल प्रक्रिया",
      step1_title: "निःशुल्क पंजीकरण",
      step1_desc: "अंग्रेजी, हिंदी, पंजाबी या ओडिया में अपना रोगी प्रोफ़ाइल बनाएं। किसी तकनीकी ज्ञान की आवश्यकता नहीं है।",
      step2_title: "एआई लक्षण जांचता है",
      step2_desc: "आवाज या पाठ द्वारा लक्षणों का वर्णन करें। एआई सही विशेषज्ञ और गंभीरता की सिफारिश करता है।",
      step3_title: "अपॉइंटमेंट बुक करें",
      step3_desc: "एक सत्यापित डॉक्टर चुनें, अपनी सुविधानुसार समय स्लॉट चुनें, और तुरंत पुष्टि प्राप्त करें।",
      step4_title: "वीडियो परामर्श",
      step4_desc: "कम बैंडविड्थ वाले वीडियो/ऑडियो कॉल में शामिल हों, निदान प्राप्त करें, और डिजिटल नुस्खा प्राप्त करें।",
      ai_header: "एआई-संचालित स्वास्थ्य सेवा",
      ai_title: "स्मार्ट निदान। सही डॉक्टर। अभी इसी वक्त।",
      ai_desc: "नैदानिक ​​​​प्रोटोकॉल पर प्रशिक्षित हमारा एआई इंजन स्थानीय भाषाओं में आपके लक्षणों का तुरंत विश्लेषण करता है और सर्वोत्तम मेल खाने वाले डॉक्टर की सिफारिश करता है।",
      ai_engine: "एआई डॉक्टर सिफारिश इंजन",
      ai_engine_desc: "90%+ सटीकता के साथ लक्षणों को सही विशेषज्ञ से मिलाता है",
      ai_multilingual: "बहुभाषी एआई सहायक",
      ai_multilingual_desc: "हिंदी, पंजाबी, ओडिया बोलता है — प्राकृतिक क्षेत्रीय भाषा सहायता",
      ai_emergency: "आपातकालीन प्राथमिकता प्रणाली",
      ai_emergency_desc: "स्वचालित रूप से गंभीरता को वर्गीकृत करता है और आपातकालीन प्रोटोकॉल को ट्रिगर करता है",
      ai_prediction: "ग्रामीण स्वास्थ्य जोखिम भविष्यवाणी",
      ai_prediction_desc: "क्षेत्रीय नाभा स्वास्थ्य डेटा का उपयोग करके मौसमी प्रकोपों ​​की भविष्यवाणी करता है",
      ai_chat_title: "रूरलकेयर एआई सहायक",
      ai_chat_subtitle: "ऑनलाइन · तुरंत जवाब देता है",
      ai_chat_placeholder: "लक्षण लिखें (जैसे छाती में दर्द, बुखार, खांसी)...",
      emergency_title: "आपातकाल: तत्काल देखभाल की आवश्यकता है?",
      emergency_desc: "एक-टैप एसओएस, एम्बुलेंस बुकिंग, ब्लड बैंक की जानकारी और नाभा सिविल अस्पताल लोकेटर।",
      emergency_btn_sos: "एसओएस अलार्म चालू करें",
      emergency_btn_amb: "एम्बुलेंस का अनुरोध करें",
      doctors_title: "500+ सत्यापित डॉक्टर मदद के लिए तैयार हैं",
      doctors_subtitle: "हमारे विशेषज्ञ",
      btn_book: "अपॉइंटमेंट बुक करें",
      patient_records_title: "रोगी डिजिटल हेल्थ वॉल्ट",
      patient_records_desc: "अपने ई-नुस्खे तक पहुंचें, मेडिकल रिपोर्ट अपलोड करें, और समय के साथ अपने स्वास्थ्य रुझानों को ट्रैक करें।",
      vitals_header: "आपका स्वास्थ्य महत्वपूर्ण इतिहास",
      prescriptions_header: "आपके डिजिटल नुस्खे",
      upload_btn: "लैब रिपोर्ट अपलोड करें",
      low_bandwidth_active: "कम-बैंडविड्थ मोड सक्रिय: मीडिया को संपीड़ित करना और ऑडियो/टेक्स्ट परामर्श को प्राथमिकता देना।",
      low_bandwidth_inactive: "सामान्य मोड: हाई-डेफिनिशन वीडियो सक्षम।"
    },
    pb: {
      nav_services: "ਸੇਵਾਵਾਂ",
      nav_doctors: "ਡਾਕਟਰ ਲੱਭੋ",
      nav_ai: "AI ਸਿਹਤ",
      nav_awareness: "ਜਾਗਰੂਕਤਾ",
      nav_contact: "ਸੰਪਰਕ ਕਰੋ",
      nav_login: "ਲੌਗਇਨ",
      nav_register: "ਮੁਫਤ ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
      hero_sih: "ਸਮਾਰਟ ਇੰਡੀਆ ਹੈਕਾਥੌਨ 2025 – SIH25018",
      hero_badge: "ਨਾਭਾ, ਪੰਜਾਬ ਲਈ ਟੈਲੀਮੈਡੀਸਨ ਪਲੇਟਫਾਰਮ",
      hero_title: "ਗੁਣਵੱਤਾ ਵਾਲੀ ਸਿਹਤ ਸੇਵਾ ਹਰ ਪਿੰਡ ਤੱਕ ਪਹੁੰਚੇ",
      hero_desc: "AI-ਦੁਆਰਾ ਸੰਚਾਲਿਤ ਟੈਲੀਮੈਡੀਸਨ ਜੋ ਨਾਭਾ ਅਤੇ ਆਸ-ਪਾਸ ਦੇ ਪੇਂਡੂ ਭਾਈਚਾਰਿਆਂ ਨੂੰ ਯੋਗ ਡਾਕਟਰਾਂ ਨਾਲ ਜੋੜਦੀ ਹੈ — ਕਿਸੇ ਵੀ ਸਮੇਂ, ਕਿਤੇ ਵੀ, ਤੁਹਾਡੀ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ।",
      btn_consult: "ਡਾਕਟਰ ਨਾਲ ਸਲਾਹ ਕਰੋ",
      btn_ai: "AI ਚੈਕਰ ਦੀ ਵਰਤੋਂ ਕਰੋ",
      stats_doctors: "ਪ੍ਰਮਾਣਿਤ ਡਾਕਟਰ",
      stats_consultations: "ਸਲਾਹ-ਮਸ਼ਵਰੇ ਹੋਏ",
      stats_specialties: "ਮਾਹਿਰ ਵਿਭਾਗ",
      stats_languages: "ਭਾਸ਼ਾਵਾਂ",
      stats_emergency: "24/7 ਐਮਰਜੈਂਸੀ ਪਹੁੰਚ",
      search_title: "ਡਾਕਟਰ, ਲੱਛਣ ਜਾਂ ਬਿਮਾਰੀਆਂ ਦੀ ਖੋਜ ਕਰੋ",
      search_placeholder: "ਲੱਛਣ, ਡਾਕਟਰ ਦਾ ਨਾਮ, ਮਾਹਰਤਾ...",
      search_location: "ਸਥਾਨ (ਨਾਭਾ, ਪਟਿਆਲਾ...)",
      search_btn: "ਡਾਕਟਰ ਲੱਭੋ",
      services_title: "ਮੁਕੰਮਲ ਪੇਂਡੂ ਸਿਹਤ ਸੰਭਾਲ ਪ੍ਰਣਾਲੀ",
      services_subtitle: "ਸਾਡੀਆਂ ਸੇਵਾਵਾਂ",
      services_desc: "ਘੱਟ ਇੰਟਰਨੈੱਟ ਸਪੀਡ ਵਾਲੇ ਖੇਤਰਾਂ ਲਈ ਤਿਆਰ ਕੀਤਾ ਗਿਆ ਹੈ, ਜੋ ਪੇਂਡੂ ਨਾਗਰਿਕਾਂ ਨੂੰ ਲੋੜੀਂਦੀਆਂ ਸਿਹਤ ਸੇਵਾਵਾਂ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ।",
      steps_title: "4 ਆਸਾਨ ਕਦਮਾਂ ਵਿੱਚ ਡਾਕਟਰ ਦੀ ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ",
      steps_subtitle: "ਸਰਲ ਪ੍ਰਕਿਰਿਆ",
      step1_title: "ਮੁਫ਼ਤ ਰਜਿਸਟਰ ਕਰੋ",
      step1_desc: "ਅੰਗਰੇਜ਼ੀ, ਹਿੰਦੀ, ਪੰਜਾਬੀ ਜਾਂ ਉੜੀਆ ਵਿੱਚ ਆਪਣੀ ਮਰੀਜ਼ ਪ੍ਰੋਫਾਈਲ ਬਣਾਓ। ਕਿਸੇ ਤਕਨੀਕੀ ਗਿਆਨ ਦੀ ਲੋੜ ਨਹੀਂ ਹੈ।",
      step2_title: "AI ਲੱਛਣਾਂ ਦੀ ਜਾਂਚ ਕਰਦਾ ਹੈ",
      step2_desc: "ਆਵਾਜ਼ ਜਾਂ ਟੈਕਸਟ ਦੁਆਰਾ ਲੱਛਣਾਂ ਦਾ ਵਰਣਨ ਕਰੋ। AI ਸਹੀ ਮਾਹਰ ਅਤੇ ਗੰਭੀਰਤਾ ਦੀ ਸਿਫਾਰਸ਼ ਕਰਦਾ ਹੈ।",
      step3_title: "ਅਪੌਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰੋ",
      step3_desc: "ਇੱਕ ਪ੍ਰਮਾਣਿਤ ਡਾਕਟਰ ਚੁਣੋ, ਆਪਣੀ ਸਹੂਲਤ ਅਨੁਸਾਰ ਸਮਾਂ ਚੁਣੋ, ਅਤੇ ਤੁਰੰਤ ਪੁਸ਼ਟੀ ਪ੍ਰਾਪਤ ਕਰੋ।",
      step4_title: "ਵੀਡੀਓ ਸਲਾਹ",
      step4_desc: "ਘੱਟ ਇੰਟਰਨੈੱਟ ਸਪੀਡ ਵਾਲੇ ਵੀਡੀਓ/ਆਡੀਓ ਕਾਲ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ, ਨਿਦਾਨ ਅਤੇ ਡਿਜੀਟਲ ਨੁਸਖ਼ਾ ਪ੍ਰਾਪਤ ਕਰੋ।",
      ai_header: "AI-ਸੰਚਾਲਿਤ ਸਿਹਤ ਸੰਭਾਲ",
      ai_title: "ਸਮਾਰਟ ਨਿਦਾਨ। ਸਹੀ ਡਾਕਟਰ। ਹੁਣੇ ਇਸੇ ਵੇਲੇ।",
      ai_desc: "ਸਾਡਾ AI ਇੰਜਣ ਸਥਾਨਕ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਤੁਹਾਡੇ ਲੱਛਣਾਂ ਦਾ ਤੁਰੰਤ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਦਾ ਹੈ ਅਤੇ ਸਭ ਤੋਂ ਵਧੀਆ ਮੇਲ ਖਾਂਦੇ ਡਾਕਟਰ ਦੀ ਸਿਫਾਰਸ਼ ਕਰਦਾ ਹੈ।",
      ai_engine: "AI ਡਾਕਟਰ ਸਿਫਾਰਸ਼ ਇੰਜਣ",
      ai_engine_desc: "90%+ ਸ਼ੁੱਧਤਾ ਨਾਲ ਲੱਛਣਾਂ ਨੂੰ ਸਹੀ ਮਾਹਰ ਨਾਲ ਮਿਲਾਉਂਦਾ ਹੈ",
      ai_multilingual: "ਬਹੁਭਾਸ਼ਾਈ AI ਸਹਾਇਕ",
      ai_multilingual_desc: "ਹਿੰਦੀ, ਪੰਜਾਬੀ, ਉੜੀਆ ਬੋਲਦਾ ਹੈ — ਕੁਦਰਤੀ ਖੇਤਰੀ ਭਾਸ਼ਾ ਸਹਾਇਤਾ",
      ai_emergency: "ਐਮਰਜੈਂਸੀ ਤਰਜੀਹ ਪ੍ਰਣਾਲੀ",
      ai_emergency_desc: "ਆਪਣੇ ਆਪ ਗੰਭੀਰਤਾ ਨੂੰ ਸ਼੍ਰੇਣੀਬੱਧ ਕਰਦਾ ਹੈ ਅਤੇ ਐਮਰਜੈਂਸੀ ਪ੍ਰੋਟੋਕੋਲ ਸ਼ੁਰੂ ਕਰਦਾ ਹੈ",
      ai_prediction: "ਪੇਂਡੂ ਸਿਹਤ ਜੋਖਮ ਭਵਿੱਖਬਾਣੀ",
      ai_prediction_desc: "ਖੇਤਰੀ ਨਾਭਾ ਸਿਹਤ ਡੇਟਾ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਮੌਸਮੀ ਬਿਮਾਰੀਆਂ ਦੀ ਭਵਿੱਖਬਾਣੀ ਕਰਦਾ ਹੈ",
      ai_chat_title: "ਰੂਰਲਕੇਅਰ AI ਸਹਾਇਕ",
      ai_chat_subtitle: "ਔਨਲਾਈਨ · ਤੁਰੰਤ ਜਵਾਬ ਦਿੰਦਾ ਹੈ",
      ai_chat_placeholder: "ਲੱਛਣ ਲਿਖੋ (ਜਿਵੇਂ ਛਾਤੀ ਵਿੱਚ ਦਰਦ, ਬੁਖਾਰ, ਖੰਘ)...",
      emergency_title: "ਐਮਰਜੈਂਸੀ: ਤੁਰੰਤ ਇਲਾਜ ਦੀ ਲੋੜ ਹੈ?",
      emergency_desc: "ਇੱਕ-ਟੈਪ SOS, ਐਂਬੂਲੈਂਸ ਬੁਕਿੰਗ, ਬਲੱਡ ਬੈਂਕ ਦੀ ਜਾਣਕਾਰੀ ਅਤੇ ਨਾਭਾ ਸਿਵਲ ਹਸਪਤਾਲ ਲੋਕੇਟਰ।",
      emergency_btn_sos: "SOS ਅਲਾਰਮ ਚਾਲੂ ਕਰੋ",
      emergency_btn_amb: "ਐਂਬੂਲੈਂਸ ਦੀ ਮੰਗ ਕਰੋ",
      doctors_title: "500+ ਪ੍ਰਮਾਣਿਤ ਡਾਕਟਰ ਮਦਦ ਲਈ ਤਿਆਰ ਹਨ",
      doctors_subtitle: "ਸਾਡੇ ਮਾਹਿਰ",
      btn_book: "ਅਪੌਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰੋ",
      patient_records_title: "ਮਰੀਜ਼ ਡਿਜੀਟਲ ਹੈਲਥ ਵਾਲਟ",
      patient_records_desc: "ਆਪਣੇ ਈ-ਨੁਸਖ਼ਿਆਂ ਤੱਕ ਪਹੁੰਚ ਕਰੋ, ਮੈਡੀਕਲ ਰਿਪੋਰਟਾਂ ਅਪਲੋਡ ਕਰੋ, ਅਤੇ ਸਮੇਂ ਦੇ ਨਾਲ ਆਪਣੇ ਸਿਹਤ ਰੁਝਾਨਾਂ ਨੂੰ ਟ੍ਰੈਕ ਕਰੋ।",
      vitals_header: "ਤੁਹਾਡੀ ਸਿਹਤ ਦਾ ਇਤਿਹਾਸ",
      prescriptions_header: "ਤੁਹਾਡੇ ਡਿਜੀਟਲ ਨੁਸਖ਼ੇ",
      upload_btn: "ਲੈਬ ਰਿਪੋਰਟ ਅਪਲੋਡ ਕਰੋ",
      low_bandwidth_active: "ਘੱਟ-ਬੈਂਡਵਿਡਥ ਮੋਡ ਸਰਗਰਮ: ਮੀਡੀਆ ਨੂੰ ਸੰਕੁਚਿਤ ਕਰਨਾ ਅਤੇ ਆਡੀਓ/ਟੈਕਸਟ ਸਲਾਹ ਨੂੰ ਤਰਜੀਹ ਦੇਣਾ।",
      low_bandwidth_inactive: "ਆਮ ਮੋਡ: ਉੱਚ-ਪਰਿਭਾਸ਼ਾ ਵੀਡੀਓ ਸਮਰੱਥ।"
    },
    or: {
      nav_services: "ସେବାସମୂହ",
      nav_doctors: "ଡାକ୍ତର ଖୋଜନ୍ତୁ",
      nav_ai: "AI ସ୍ୱାସ୍ଥ୍ୟ",
      nav_awareness: "ସଚେତନତା",
      nav_contact: "ଯୋଗାଯୋଗ",
      nav_login: "ଲଗଇନ୍",
      nav_register: "ମାଗଣା ପଞ୍ଜୀକରଣ",
      hero_sih: "ସ୍ମାର୍ଟ ଇଣ୍ଡିଆ ହାକାଥନ୍ ୨୦୨୫ – SIH25018",
      hero_badge: "ନାଭା, ପଞ୍ଜାବ ପାଇଁ ଟେଲିମେଡିସିନ୍ ପ୍ଲାଟଫର୍ମ",
      hero_title: "ଗୁଣାତ୍ମକ ସ୍ୱାସ୍ଥ୍ୟ ସେବା ପ୍ରତି ଗାଁରେ ପହଞ୍ଚୁ",
      hero_desc: "AI-ଦ୍ୱାରା ପରିଚାଳିତ ଟେଲିମେଡିସିନ୍ ଯାହା ନାଭା ଏବଂ ଆଖପାଖର ଗ୍ରାମୀଣ ସମୁଦାୟକୁ ଯୋଗ୍ୟ ଡାକ୍ତରଙ୍କ ସହ ଯୋଡିଥାଏ - ଯେକୌଣସି ସମୟରେ, ଯେକୌଣସି ସ୍ଥାନରେ, ଆପଣଙ୍କ ଭାଷାରେ।",
      btn_consult: "ଡାକ୍ତରଙ୍କ ପରାମର୍ଶ ନିଅନ୍ତୁ",
      btn_ai: "AI ଚେକର୍ ବ୍ୟବହାର କରନ୍ତୁ",
      stats_doctors: "ଯାଞ୍ଚ ହୋଇଥିବା ଡାକ୍ତର",
      stats_consultations: "ପରାମର୍ଶ ସମାପ୍ତ",
      stats_specialties: "ବିଶେଷଜ୍ଞ ବିଭାଗ",
      stats_languages: "ଭାଷା",
      stats_emergency: "୨୪/୭ ଜରୁରୀକାଳୀନ ସେବା",
      search_title: "ଡାକ୍ତର, ଲକ୍ଷଣ କିମ୍ବା ରୋଗ ଖୋଜନ୍ତୁ",
      search_placeholder: "ଲକ୍ଷଣ, ଡାକ୍ତରଙ୍କ ନାମ, ବିଶେଷଜ୍ଞତା...",
      search_location: "ସ୍ଥାନ (ନାଭା, ପଟିଆଲା...)",
      search_btn: "ଡାକ୍ତର ଖୋଜନ୍ତୁ",
      services_title: "ସମ୍ପୂର୍ଣ୍ଣ ଗ୍ରାମୀଣ ସ୍ୱାସ୍ଥ୍ୟସେବା ବ୍ୟବସ୍ଥା",
      services_subtitle: "ଆମର ଅଫର୍",
      services_desc: "କମ୍ ଇଣ୍ଟରନେଟ୍ ସ୍ପିଡ୍ ପାଇଁ ଡିଜାଇନ୍ ହୋଇଛି, ଯାହା ଗ୍ରାମୀଣ ନାଗରିକଙ୍କୁ ଆବଶ୍ୟକୀୟ ସ୍ୱାସ୍ଥ୍ୟ ସେବା ଯୋଗାଇଥାଏ।",
      steps_title: "୪ଟି ସହଜ ସୋପାନରେ ଡାକ୍ତରଙ୍କ ପରାମର୍ଶ ପାଆନ୍ତୁ",
      steps_subtitle: "ସରଳ ପ୍ରକ୍ରିୟା",
      step1_title: "ମାଗଣା ପଞ୍ଜୀକରଣ କରନ୍ତୁ",
      step1_desc: "ଇଂରାଜୀ, ହିନ୍ଦୀ, ପଞ୍ଜାବୀ କିମ୍ବା ଓଡ଼ିଆରେ ଆପଣଙ୍କ ରୋଗୀ ପ୍ରୋଫାଇଲ୍ ତିଆରି କରନ୍ତୁ। କୌଣସି ବୈଷୟିକ ଜ୍ଞାନ ଆବଶ୍ୟକ ନାହିଁ।",
      step2_title: "AI ଲକ୍ଷଣ ଯାଞ୍ଚ କରେ",
      step2_desc: "ସ୍ୱର କିମ୍ବା ଲେଖା ଦ୍ୱାରା ଲକ୍ଷଣ ବର୍ଣ୍ଣନା କରନ୍ତୁ। AI ସଠିକ୍ ବିଶେଷଜ୍ଞ ଏବଂ ଗୁରୁତରତା ସୁପାରିଶ କରେ।",
      step3_title: "ନିଯୁକ୍ତି ବୁକ୍ କରନ୍ତୁ",
      step3_desc: "ଜଣେ ଯାଞ୍ଚ ହୋଇଥିବା ଡାକ୍ତର ବାଛନ୍ତୁ, ନିଜ ସୁବିଧା ଅନୁସାରେ ସମୟ ସ୍ଲଟ୍ ବାଛନ୍ତୁ ଏବଂ ତୁରନ୍ତ ନିଶ୍ଚିତତା ପାଆନ୍ତୁ।",
      step4_title: "ଭିଡିଓ ପରାମର୍ଶ",
      step4_desc: "କମ୍ ଇଣ୍ଟରନେଟ୍ ସ୍ପିଡ୍ ଥିବା ଭିଡିଓ/ଅଡିଓ କଲ୍‌ରେ ଯୋଗ ଦିଅନ୍ତୁ, ରୋଗ ନିରୂପଣ ଏବଂ ଡିଜିଟାଲ୍ ପ୍ରେସକ୍ରିପସନ୍ ପାଆନ୍ତୁ।",
      ai_header: "AI-ପରିଚାଳିତ ସ୍ୱାସ୍ଥ୍ୟସେବା",
      ai_title: "ସ୍ମାର୍ଟ ରୋଗ ଚିହ୍ନଟ। ସଠିକ୍ ଡାକ୍ତର। ଏବେ ହିଁ।",
      ai_desc: "ଆମର AI ଇଞ୍ଜିନ୍ ସ୍ଥାନୀୟ ଭାଷାରେ ଆପଣଙ୍କ ଲକ୍ଷଣର ତୁରନ୍ତ ବିଶ୍ଳେଷଣ କରେ ଏବଂ ସର୍ବୋତ୍ତମ ମେଳ ଖାଉଥିବା ଡାକ୍ତରଙ୍କୁ ସୁପାରିଶ କରେ।",
      ai_engine: "AI ଡାକ୍ତର ସୁପାରିଶ ଇଞ୍ଜିନ୍",
      ai_engine_desc: "୯୦%+ ସଠିକତା ସହିତ ଲକ୍ଷଣକୁ ସଠିକ୍ ବିଶେଷଜ୍ଞଙ୍କ ସହ ମିଶାଏ",
      ai_multilingual: "ବହୁଭାଷୀ AI ସହାୟକ",
      ai_multilingual_desc: "ହିନ୍ଦୀ, ପଞ୍ଜାବୀ, ଓଡ଼ିଆ କହେ — ପ୍ରାକୃତିକ ଆଞ୍ଚଳିକ ଭାଷା ସହାୟତା",
      ai_emergency: "ଜରୁରୀକାଳୀନ ପ୍ରାଥମିକତା ପ୍ରଣାଳୀ",
      ai_emergency_desc: "ସ୍ୱୟଂଚାଳିତ ଭାବରେ ଗୁରୁତରତା ଶ୍ରେଣୀଭୁକ୍ତ କରେ ଏବଂ ଜରୁରୀକାଳୀନ ପ୍ରୋଟୋକଲ୍ ସକ୍ରିୟ କରେ",
      ai_prediction: "ଗ୍ରାମୀଣ ସ୍ୱାସ୍ଥ୍ୟ ବିପଦ ପୂର୍ବାନୁମାନ",
      ai_prediction_desc: "ଆଞ୍ଚଳିକ ନାଭା ସ୍ୱାସ୍ଥ୍ୟ ତଥ୍ୟ ବ୍ୟବହାର କରି ଋତୁକାଳୀନ ରୋଗର ପୂର୍ବାନୁମାନ କରେ",
      ai_chat_title: "ରୁରାଲ୍‌କେୟାର AI ସହାୟକ",
      ai_chat_subtitle: "ଅନ୍‌ଲାଇନ୍ · ତୁରନ୍ତ ଉତ୍ତର ଦିଏ",
      ai_chat_placeholder: "ଲକ୍ଷଣ ଟାଇପ୍ କରନ୍ତୁ (ଯେପରିକି ଛାତିରେ ଯନ୍ତ୍ରଣା, ଜ୍ୱର, କାଶ)...",
      emergency_title: "ଜରୁରୀକାଳୀନ: ତୁରନ୍ତ ଯତ୍ନ ଆବଶ୍ୟକ କି?",
      emergency_desc: "ୱାନ୍-ଟ୍ୟାପ୍ SOS, ଆମ୍ବୁଲାନ୍ସ ବୁକିଂ, ରକ୍ତ ଭଣ୍ଡାର ସୂଚନା ଏବଂ ନାଭା ସିଭିଲ୍ ହସ୍ପିଟାଲ୍ ଲୋକେଟର।",
      emergency_btn_sos: "SOS ଆଲାର୍ମ ସକ୍ରିୟ କରନ୍ତୁ",
      emergency_btn_amb: "ଆମ୍ବୁଲାନ୍ସ ଅନୁରୋଧ କରନ୍ତୁ",
      doctors_title: "୫୦୦+ ଯାଞ୍ଚ ହୋଇଥିବା ଡାକ୍ତର ସାହାଯ୍ୟ ପାଇଁ ପ୍ରସ୍ତୁତ",
      doctors_subtitle: "ଆମର ବିଶେଷଜ୍ଞ",
      btn_book: "ନିଯୁକ୍ତି ବୁକ୍ କରନ୍ତୁ",
      patient_records_title: "ରୋଗୀ ଡିଜିଟାଲ୍ ସ୍ୱାସ୍ଥ୍ୟ ସିନ୍ଦୁକ",
      patient_records_desc: "ଆପଣଙ୍କର ଇ-ପ୍ରେସକ୍ରିପସନ୍ ଦେଖନ୍ତୁ, ମେଡିକାଲ୍ ରିପୋର୍ଟ ଅପ୍‌ଲୋଡ୍ କରନ୍ତୁ ଏବଂ ସମୟ ସହିତ ଆପଣଙ୍କ ସ୍ୱାସ୍ଥ୍ୟ ସୂଚନା ଟ୍ରାକ୍ କରନ୍ତୁ।",
      vitals_header: "ଆପଣଙ୍କ ସ୍ୱାସ୍ଥ୍ୟର ଇତିହାସ",
      prescriptions_header: "ଆପଣଙ୍କ ଡିଜିଟାଲ୍ ପ୍ରେସକ୍ରିପସନ୍",
      upload_btn: "ଲ୍ୟାବ୍ ରିପୋର୍ଟ ଅପ୍‌ଲୋଡ୍ କରନ୍ତୁ",
      low_bandwidth_active: "କମ୍-ବ୍ୟାଣ୍ଡୱିଡଥ୍ ମୋଡ୍ ସକ୍ରିୟ: ମିଡିଆ ସଙ୍କୁଚିତ ହେଉଛି ଏବଂ ଅଡିଓ/ଟେକ୍ସଟ୍ ପରାମର୍ଶକୁ ପ୍ରାଥମିକତା ଦିଆଯାଉଛି।",
      low_bandwidth_inactive: "ସାଧାରଣ ମୋଡ୍: ହାଇ-ଡେଫିନିସନ୍ ଭିଡିଓ ସକ୍ଷମ ଅଛି।"
    }
  },

  // Mock Doctors List (associated with Nabha/Punjab region)
  doctors: [
    {
      id: "doc-1",
      name: "Dr. Siva prasad Rath",
      specialty: "General Physician",
      experience: 14,
      rating: 4.9,
      patients: "2.1K",
      languages: ["English", "Hindi", "Punjabi"],
      fee: 299,
      online: true,
      avatar: "👨‍⚕️",
      clinic: "AIIMS Delhi / Nabha Clinic Link"
    },
    {
      id: "doc-2",
      name: "Dr. Shatabdi Satapathy",
      specialty: "Cardiologist",
      experience: 9,
      rating: 4.7,
      patients: "4.8K",
      languages: ["Hindi", "Punjabi"],
      fee: 150,
      online: true,
      avatar: "👩‍⚕️",
      clinic: "Civil Hospital Nabha"
    },
    {
      id: "doc-3",
      name: "Dr. Sidharth Sahoo",
      specialty: "Pediatrician",
      experience: 12,
      rating: 4.8,
      patients: "3.2K",
      languages: ["English", "Punjabi"],
      fee: 200,
      online: true,
      avatar: "👨‍⚕️",
      clinic: "Patiala District Children Hospital"
    },
    {
      id: "doc-4",
      name: "Dr. Satya Narayan",
      specialty: "Gynecologist",
      experience: 15,
      rating: 4.9,
      patients: "5.5K",
      languages: ["English", "Hindi", "Odia"],
      fee: 250,
      online: true,
      avatar: "👩‍⚕️",
      clinic: "Nabha Maternal Center"
    },
    {
      id: "doc-5",
      name: "Dr. Baka",
      specialty: "Orthopedic",
      experience: 18,
      rating: 4.6,
      patients: "1.9K",
      languages: ["Hindi", "Punjabi"],
      fee: 300,
      online: false,
      avatar: "👨‍⚕️",
      clinic: "Nabha Ortho Care"
    },
    {
      id: "doc-6",
      name: "Dr. Sourav",
      specialty: "Dermatologist",
      experience: 8,
      rating: 4.7,
      patients: "2.4K",
      languages: ["English", "Hindi"],
      fee: 220,
      online: true,
      avatar: "👩‍⚕️",
      clinic: "Skin & Laser Center Patiala"
    },
    {
      id: "doc-7",
      name: "Dr. Sahil",
      specialty: "ENT Specialist",
      experience: 11,
      rating: 4.8,
      patients: "1.5K",
      languages: ["English", "Hindi", "Punjabi"],
      fee: 180,
      online: true,
      avatar: "👨‍⚕️",
      clinic: "Nabha ENT & Hearing Clinic"
    }
  ],

  // Hospitals & Emergency Services in Nabha / Patiala
  hospitals: [
    {
      name: "Nabha Civil Hospital",
      location: "Circular Road, Nabha",
      distance: 1.2,
      beds: 14,
      icus: 3,
      phone: "+91-1765-220012",
      coords: { lat: 30.3732, lng: 76.1512 }
    },
    {
      name: "Patiala District Hospital (Rajindra Hospital)",
      location: "Sangrur Road, Patiala (Near Nabha)",
      distance: 24.5,
      beds: 125,
      icus: 18,
      phone: "+91-175-2212542",
      coords: { lat: 30.3398, lng: 76.3869 }
    },
    {
      name: "Nabha Community Health Centre (CHC)",
      location: "Bhadson Sector, Nabha Rural",
      distance: 8.7,
      beds: 6,
      icus: 0,
      phone: "+91-1765-284050",
      coords: { lat: 30.4512, lng: 76.1824 }
    }
  ],

  // Symptom checker matching rule matrix
  symptomMatrix: {
    chest_pain: {
      specialty: "Cardiologist",
      urgency: "High",
      urgencyClass: "urgent",
      priorityText: {
        en: "🔴 HIGH – Immediate Cardiac Attention Required",
        hi: "🔴 उच्च – तत्काल कार्डियक ध्यान की आवश्यकता है",
        pb: "🔴 ਉੱਚ – ਤੁਰੰਤ ਦਿਲ ਦੇ ਮਾਹਰ ਦੀ ਸਲਾਹ ਦੀ ਲੋੜ ਹੈ",
        or: "🔴 ଉଚ୍ଚ – ତୁରନ୍ତ ହୃଦରୋଗ ଚିକିତ୍ସା ଆବଶ୍ୟକ"
      },
      advice: {
        en: "Keep calm. Sit down in a comfortable position. Chew a 325mg aspirin if available. Avoid exertion. We recommend booking an immediate video consult or calling SOS.",
        hi: "शांत रहें। आरामदायक स्थिति में बैठ जाएं। यदि उपलब्ध हो, तो 325mg एस्पिरिन चबाएं। परिश्रम से बचें। हम तुरंत वीडियो परामर्श बुक करने या एसओएस कॉल करने की सलाह देते हैं।",
        pb: "ਸ਼ਾਂਤ ਰਹੋ। ਆਰਾਮਦਾਇਕ ਸਥਿਤੀ ਵਿੱਚ ਬੈਠੋ। ਜੇਕਰ ਉਪਲਬਧ ਹੋਵੇ, 325mg ਐਸਪਰੀਨ ਚਬਾਓ। ਜ਼ੋਰ ਲਗਾਉਣ ਤੋਂ ਬਚੋ। ਅਸੀਂ ਤੁਰੰਤ ਵੀਡੀਓ ਸਲਾਹ ਬੁੱਕ ਕਰਨ ਜਾਂ SOS ਕਰਨ ਦੀ ਸਲਾਹ ਦਿੰਦੇ ਹਾਂ।",
        or: "ଶାନ୍ତ ରୁହନ୍ତୁ। ଆରାମଦାୟକ ସ୍ଥିତିରେ ବସନ୍ତୁ। ଯଦି ଉପଲବ୍ଧ ଥାଏ, ଗୋଟିଏ ୩୨୫mg ଆସପିରିନ୍ ଚୋବାଇ ଖାଆନ୍ତୁ। ପରିଶ୍ରମ କରନ୍ତୁ ନାହିଁ। ଆମେ ତୁରନ୍ତ ଭିଡିଓ ପରାମର୍ଶ କିମ୍ବା SOS କଲ୍ କରିବାକୁ ସୁପାରିଶ କରୁଛୁ।"
      },
      confidence: "94%"
    },
    fever: {
      specialty: "General Physician",
      urgency: "Medium",
      urgencyClass: "medium",
      priorityText: {
        en: "🟡 MEDIUM – General Health Assessment",
        hi: "🟡 मध्यम – सामान्य स्वास्थ्य मूल्यांकन",
        pb: "🟡 ਮੱਧਮ – ਆਮ ਸਿਹਤ ਮੁਲਾਂਕਣ",
        or: "🟡 ମଧ୍ୟମ – ସାଧାରଣ ସ୍ୱାସ୍ଥ୍ୟ ଯାଞ୍ଚ"
      },
      advice: {
        en: "Drink plenty of fluids, rest, and keep a log of your temperature readings. Take paracetamol if temperature goes above 100°F. If fever persists for >3 days, consult a physician.",
        hi: "खूब सारे तरल पदार्थ पीएं, आराम करें और अपने शरीर के तापमान का रिकॉर्ड रखें। यदि तापमान 100°F से ऊपर जाता है तो पैरासिटामोल लें। यदि बुखार 3 दिनों से अधिक रहता है, तो डॉक्टर से मिलें।",
        pb: "ਬਹੁਤ ਸਾਰਾ ਪਾਣੀ ਪੀਓ, ਆਰਾਮ ਕਰੋ ਅਤੇ ਆਪਣੇ ਸਰੀਰ ਦੇ ਤਾਪਮਾਨ ਦਾ ਰਿਕਾਰਡ ਰੱਖੋ। ਜੇਕਰ ਤਾਪਮਾਨ 100°F ਤੋਂ ਉੱਪਰ ਜਾਂਦਾ ਹੈ ਤਾਂ ਪੈਰਾਸੀਟਾਮੋਲ ਲਓ। ਜੇਕਰ ਬੁਖਾਰ 3 ਦਿਨਾਂ ਤੋਂ ਵੱਧ ਰਹਿੰਦਾ ਹੈ, ਤਾਂ ਡਾਕਟਰ ਨੂੰ ਦਿਖਾਓ।",
        or: "ପ୍ରଚୁର ପରିମାଣରେ ପାଣି ପିଅନ୍ତୁ, ବିଶ୍ରାମ ନିଅନ୍ତୁ ଏବଂ ଜ୍ୱର ମାପି ଲେଖି ରଖନ୍ତୁ। ଯଦି ଜ୍ୱର ୧୦୦°F ରୁ ଅଧିକ ହୁଏ ତେବେ ପାରାସିଟାମଲ୍ ନିଅନ୍ତୁ। ଯଦି ଜ୍ୱର ୩ ଦିନରୁ ଅଧିକ ରୁହେ, ଡାକ୍ତରଙ୍କ ସହ ପରାମର୍ଶ କରନ୍ତୁ।"
      },
      confidence: "88%"
    },
    child_fever: {
      specialty: "Pediatrician",
      urgency: "Medium-High",
      urgencyClass: "medium-high",
      priorityText: {
        en: "🟠 MEDIUM-HIGH – Pediatric Consult Recommended",
        hi: "🟠 मध्यम-उच्च – बाल रोग विशेषज्ञ परामर्श अनुशंसित",
        pb: "🟠 ਮੱਧਮ-ਉੱਚ – ਬੱਚਿਆਂ ਦੇ ਮਾਹਰ ਦੀ ਸਲਾਹ ਦੀ ਲੋੜ ਹੈ",
        or: "🟠 ମଧ୍ୟମ-ଉଚ୍ଚ – ଶିଶୁ ରୋଗ ବିଶେଷଜ୍ଞ ପରାମର୍ଶ ସୁପାରିଶ"
      },
      advice: {
        en: "Ensure the child is hydrated. Do not wrap in thick blankets. Give paracetamol strictly matching child dosage chart based on weight. Consult a pediatrician promptly.",
        hi: "सुनिश्चित करें कि बच्चे के शरीर में पानी की कमी न हो। उसे मोटे कंबलों में न लपेटें। वजन के अनुसार बाल चिकित्सा खुराक चार्ट से मिलाकर ही पैरासिटामोल दें। तुरंत बाल रोग विशेषज्ञ से संपर्क करें।",
        pb: "ਯਕੀਨੀ ਬਣਾਓ ਕਿ ਬੱਚੇ ਦੇ ਸਰੀਰ ਵਿੱਚ ਪਾਣੀ ਦੀ ਕਮੀ ਨਾ ਹੋਵੇ। ਉਸਨੂੰ ਮੋਟੇ ਕੰਬਲ ਵਿੱਚ ਨਾ ਲਪੇਟੋ। ਭਾਰ ਦੇ ਅਨੁਸਾਰ ਪੈਰਾਸੀਟਾਮੋਲ ਦੀ ਸਹੀ ਖੁਰਾਕ ਦਿਓ। ਤੁਰੰਤ ਬੱਚਿਆਂ ਦੇ ਡਾਕਟਰ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।",
        or: "ଶିଶୁ ଯେପରି ଅଧିକ ପାଣି ପିଇବ ତାହା ନିଶ୍ଚିତ କରନ୍ତୁ। ମୋଟା କମ୍ବଳ ଘୋଡାନ୍ତୁ ନାହିଁ। ଶିଶୁର ଓଜନ ଅନୁସାରେ ପାରାସିଟାମଲ୍ ଦିଅନ୍ତୁ। ତୁରନ୍ତ ଶିଶୁ ରୋਗ ବିଶେଷଜ୍ଞଙ୍କ ସହ ପରାମର୍ଶ କରନ୍ତୁ।"
      },
      confidence: "91%"
    },
    skin_rash: {
      specialty: "Dermatologist",
      urgency: "Low",
      urgencyClass: "low",
      priorityText: {
        en: "🟢 LOW – Dermatological Evaluation",
        hi: "🟢 कम – त्वचा विज्ञान मूल्यांकन",
        pb: "🟢 ਘੱਟ – ਚਮੜੀ ਦੇ ਰੋਗਾਂ ਦਾ ਮੁਲਾਂਕਣ",
        or: "🟢 କମ୍ – ଚର୍ମରୋଗ ଯାଞ୍ଚ"
      },
      advice: {
        en: "Avoid scratching or applying harsh soaps/cosmetics to the affected area. Cool compresses may ease itching. Keep the area clean and dry. Book an online appointment with our dermatologist.",
        hi: "प्रभावित क्षेत्र को खुजलाने या वहां कठोर साबुन/सौंदर्य प्रसाधन लगाने से बचें। ठंडी सिकाई से खुजली कम हो सकती है। क्षेत्र को साफ और सूखा रखें। हमारे त्वचा विशेषज्ञ के साथ ऑनलाइन अपॉइंटमेंट बुक करें।",
        pb: "ਪ੍ਰਭਾਵਿਤ ਹਿੱਸੇ ਨੂੰ ਖੁਰਕਣ ਜਾਂ ਉੱਥੇ ਕਠੋਰ ਸਾਬਣ/ਕਾਸਮੈਟਿਕਸ ਲਗਾਉਣ ਤੋਂ ਬਚੋ। ਠੰਡੀ ਸਿਕਾਈ ਨਾਲ ਖਾਰਸ਼ ਘੱਟ ਹੋ ਸਕਦੀ ਹੈ। ਖੇਤਰ ਨੂੰ ਸਾਫ਼ ਅਤੇ ਸੁੱਕਾ ਰੱਖੋ। ਚਮੜੀ ਦੇ ਮਾਹਰ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।",
        or: "ଆକ୍ରାନ୍ତ ସ୍ଥାନକୁ କୁଣ୍ଡାନ୍ତୁ ନାହିଁ କିମ୍ବା କୌଣସି କଡା ସାବୁନ୍ ଲଗାନ୍ତୁ ନାହିଁ। ଥଣ୍ଡା ପାଣିରେ ସେକ ଦେଲେ କୁଣ୍ଡେଇ ହେବା କମିପାରେ। ସ୍ଥାନଟିକୁ ସଫା ଓ ଶୁଖିଲା ରଖନ୍ତୁ। ଡର୍ମାଟୋଲୋଜିଷ୍ଟଙ୍କ ସହ ଆପଏଣ୍ଟମେଣ୍ଟ ବୁକ୍ କରନ୍ତୁ।"
      },
      confidence: "85%"
    },
    pregnancy_check: {
      specialty: "Gynecologist",
      urgency: "Low-Medium",
      urgencyClass: "low-medium",
      priorityText: {
        en: "🟢 LOW-MEDIUM – Prenatal & Women's Health Advice",
        hi: "🟢 कम-मध्यम – प्रसवपूर्व और महिला स्वास्थ्य सलाह",
        pb: "🟢 ਘੱਟ-ਮੱਧਮ – ਜਣੇਪਾ ਅਤੇ ਮਹਿਲਾ ਸਿਹਤ ਸਲਾਹ",
        or: "🟢 କମ୍-ମଧ୍ୟମ – ଗର୍ଭବତୀ ଓ ମହିଳା ସ୍ୱାସ୍ଥ୍ୟ ପରାମର୍ଶ"
      },
      advice: {
        en: "Ensure regular intake of folic acid, iron supplements, and maintain a balanced diet. Stay hydrated and monitor fetal kicks (if in 2nd/3rd trimester). Book a routine gynae consultation.",
        hi: "नियमित रूप से फोलिक एसिड, आयरन सप्लीमेंट लें और संतुलित आहार बनाए रखें। पर्याप्त पानी पीएं और भ्रूण की हलचल की निगरानी करें। नियमित स्त्री रोग परामर्श बुक करें।",
        pb: "ਨਿਯਮਿਤ ਤੌਰ 'ਤੇ ਫੋਲਿਕ ਐਸਿਡ, ਆਇਰਨ ਦੀਆਂ ਗੋਲੀਆਂ ਲਓ ਅਤੇ ਸੰਤੁਲਿਤ ਖੁਰਾਕ ਖਾਓ। ਭਰਪੂਰ ਪਾਣੀ ਪੀਓ ਅਤੇ ਬੱਚੇ ਦੀ ਹਲਚਲ 'ਤੇ ਨਜ਼ਰ ਰੱਖੋ। ਇਸਤਰੀ ਰੋਗਾਂ ਦੇ ਡਾਕਟਰ ਨਾਲ ਸਲਾਹ ਕਰੋ।",
        or: "ନିୟମିତ ଭାବେ ଫୋଲିକ୍ ଏସିଡ୍ ଏବଂ ଆଇରନ୍ ବଟିକା ସେବନ କରନ୍ତୁ ଏବଂ ସନ୍ତୁଳିତ ଆହାର ନିଅନ୍ତୁ। ପ୍ରଚୁର ପାଣି ପିଅନ୍ତୁ। ଜଣେ ସ୍ତ୍ରୀ ରୋଗ ବିଶେଷଜ୍ଞଙ୍କ ସହ ନିୟମିତ ପରାମର୍ଶ କରନ୍ତୁ।"
      },
      confidence: "90%"
    }
  }
};
